export enum BUILDING_TYPES {
  BROKEN_CISTERN = "Broken Cistern",
  DECAYING_STUDY = "Decaying Study",
  RUINED_HUTS = "Ruined Huts",
  FALLOW_FIELD = "Fallow Field",
  SHATTERED_GATE = "Shattered Gate",
  ABANDONED_MARKET = "Abandoned Market",
  CISTERN = "Cistern",
  STUDY = "Study",
  HUTS = "Huts",
  LENTIL_FIELD = "Lentil Field",
  REED_DELTA = "Reed Delta",
  GRAIN_FIELD = "Grain Field",
  OLIVE_GROVE = "Olive Grove",
  QUAIL_PASTURE = "Quail Pasture",
  GATE = "Gate",
  MARKET = "Market",
  CLAY_PIT = "Clay Pit",
  SAND_PIT = "Sand Pit",
  DRYING_YARD = "Drying Yard",
  PRESS = "Press",
  FURNACE = "Furnace",
  KITCHEN = "Kitchen"
}
