export enum FORTUITIES {
  FAMILIAR_FIGURE = "A Familiar Figure",
  UNREPENTANT_FIGURE = "An Unrepentant Figure",
  SLIGHT_FIGURE = "A Slight Figure",
  CHEERY_FIGURE = "A Cheery Figure",
  LIMPING_FIGURE = "A Limping Figure",
  BELLIGERENT_FIGURE = "A Belligerent Figure",
  THE_NOBLE_DROMEDARY = "The Noble Dromedary",
  BARTERING_DROMEDARY = "Dromedarian: Bartering for Dromedaries",
  A_SUSPICION_DROMEDARIAN = "Dromedarian: A Suspicion",
  SOUTHERN_WADI = "Dromedarian: The Sourthern Wadi",
  SIMPLE_TOOLS_WATER_EARTH = "Simple Tools: Water and Earth",
  SIMPLE_TOOLS_FIRE_LEAVES = "Simple Tools: Fire and Leaves",
  RAIN = "Rain",
  UNSPEAKING = "Unspeaking",
  FIERCE_WIND = "Fierce Wind",
  BURIED_SHIP = "Buried Ship",
  UNUSUAL_SOIL = "Unusual Soil",
  THRICE_LOCKED_TOME = "Thrice Locked Tome",
  A_TERRACED_PLATFORM = "A Terraced Platform",
  A_SANDSTONE_THROUGHWAY = "A Sandstone Throughway",
  SPRING_AUTUMN_PROOFS = "Proofs for the Spring-Autumn Kingdom",
  A_SOILED_YET_SHINING_GOWN = "A Soiled Yet Shining Gown"
}
