export enum MEMOS {
  INTRO_ONE = "Intro One",
  INTRO_TWO = "Intro Two",
  LOOK_AROUND = "Look Around",
  LOOK_AROUND_LOOT = "Look Around Loot",
  LOOK_AROUND_REPAIR = "Look Around Repair",
  CISTERN_REPAIRED = "Cistern Built",
  CISTERN_REPAIRED_NEXT = "Cistern Built Next",
  FIELD_REPAIRED = "Field Repaired",
  FIELD_REPAIRED_NEXT = "Field Repaired Next",
  MARKET_REPAIRED = "Market Repaired",
  MARKET_REPAIRED_NEXT = "Market Repaired Next",
  STUDY_REPAIRED = "Study Repaired",
  STUDY_REPAIRED_NEXT = "Study Repaired Next",
}
