export enum MODALS {
  SPOT = "Spot",
  BUILDING_DETAIL = "Building Detail",
  BUILD_DETAIL = "Build Detail",
  LEADER_DETAIL = "Leader Detail",
  RESOURCE_DETAIL = "Resource Detail",
  RESOURCE_SELECT = "Resource Select",
  RESOURCE_SELECT_ONE = "Resource Select One",
  RESOURCE_SELECT_DISH = "Resource Select Dish",
  RESOURCE_SELECT_RATE = "Resource Select Rate",
  LEADER_SELECT = "Leader Select",
  BUILDING_SELECT = "Building Select",
  EQUIPMENT_SELECT = "Equipment Select",
  DESTINATION_SELECT = "Destination Select",
  EQUIPMENT_MARKED_ONE = "Equipment Marked One",
  EQUIPMENT_MARKED_ALL = "Equipment Marked All",
  EQUIPMENT_DETAIL = "Equipment Detail",
  MEMO = "Memo",
  LOGIN = "Login",
  SIGNUP = "Signup",
  QUEST_QUIT_CONFIRM = "Quest Quit Confirm",
  MESSAGES = "Messages"
}
