export enum RESEARCHES {
  SCHOLARSHIP = "Scholarship",
  STUDY = "Study",
  ANALYSIS = "Analysis",
  CONJECTURE = "Conjecture",
  BIOLOGY = "Biology",
  LENTIL_FARMING = "Lentil Farming",
  SIMPLIFIED_LENTIL_FARMING = "Simplified Lentil Farming",
  REED_CULTIVATION = "Reed Cultivation",
  GRAIN_FARMING = "Grain Farming",
  SIMPLIFIED_GRAIN_FARMING = "Simplified Grain Farming",
  OLIVE_FARMING = "Olive Farming",
  SIMPLIFIED_OLIVE_FARMING = "Simplified Olive Farming",
  MULCH = "Mulch",
  ANTHROPOLOGY = "Anthropology",
  TRADING = "Trading",
  PHYSICS = "Physics",
  CLAY_EXCAVATION = "Clay Excavation",
  SAND_EXCAVATION = "Sand Excavation",
  COMPACTION = "Compaction",
  CHEMISTRY = "Chemistry",
  DEHYDRATION = "Dehydration",
  COMBUSTION = "Combustion"
}
