export enum RESOURCE_TAGS {
  MIND = "Mind",
  DRINK = "Drink",
  CROP = "Crop",
  FRUIT = "Fruit",
  ANIMAL = "Animal",
  EARTH = "Earth",
  FOOD = "Food",
  PROVISION = "Provision",
  CONSTRUCTION = "Construction",
  FUEL = "Fuel",
  FUEL_POTENT = "Potent Fuel",
  PRECIOUS = "Precious",
  TRADE_GOOD = "Trade Good",
  PRESSED = "Pressed",
  DRIED = "Dried",
  POWDER = "Powder",
  TEXTILE = "Textile",
  GLASS = "Glass",
  SYNTHESIZED = "Synthesized",
  SMELTED = "Smelted",
  INGREDIENT = "Cooking Ingredient",
  CERAMIC = "Ceramic",
  SPICE = "Cooking Spice",
  ACTION_SEEK = "Action: Seek",
  ACTION_BREAK = "Action: Break",
  ACTION_TRAP = "Action: Trap",
  ACTION_LOOSE = "Action: Loose",
  ACTION_HEAL = "Action: Heal",
  SAVORY = "Savory", // orange
  SWEET = "Sweet", // pink
  BITTER = "Bitter", // purple
  SOUR = "Sour", // yellow
  BRACKISH = "Brackish", // dark blue
  SPICY = "Spicy", // red
  COOLING = "Cooling", // light blue
  HERBAL = "Herbal" // green
}
