export enum RESOURCE_TYPES {
  KNOWLEDGE = "Knowledge",
  WATER = "Water",
  LENTILS = "Lentils",
  REEDS = "Reeds",
  SEEDS = "Seeds",
  GRAIN = "Grain",
  OLIVES = "Olives",
  WOOD_OAK = "Oak Wood",
  WOOD_ROWAN = "Rowan Wood",
  WOOD_WALNUT = "Walnut Wood",
  WOOD_ALDER = "Alder Wood",
  WOOD_MAPLE = "Maple Wood",
  WOOD_WILLOW = "Willow Wood",
  WOOD_ASH = "Ash Wood",
  WOOD_SPRUCE = "Spruce Wood",
  CLAY_RED = "Red Clay",
  BRICKS_RED = "Red Bricks",
  THATCH = "Thatch",
  SAND_YELLOW = "Yellow Sand",
  SALT = "Salt",
  OLIVE_OIL = "Olive Oil",
  GLASS = "Glass",
  PULP = "Pulp",
  PAPYRUS = "Papyrus",
  LENTIL_SOUP = "Lentil Soup",
  BREAD = "Bread"
}
