export enum SVGS {
  KNOWLEDGE = "Knowledge",
  LENTILS = "Lentils",
  WATER = "Water",
  SEEDS = "Seeds",
  REEDS = "Reeds",
  GRAIN = "Grain",
  FLOUR = "Flour",
  OLIVES = "Olives",
  QUAIL = "Quail",
  EGGS = "Eggs",
  FERTILIZER = "Fertilizer",
  OXEN = "Oxen",
  MILK = "Milk",
  SILKWORM_COCOON = "Silkworm Cocoon",
  WOOD = "Wood",
  CLAY = "Clay",
  BRICK = "Brick",
  THATCH = "Thatch",
  SAND = "Sand",
  CHARCOAL = "Charcoal",
  CARBON = "Carbon",
  ORE = "Ore",
  POWDER = "Powder",

  PULP = "Pulp",
}
